### ISSUE TITLE
Encryption not working

### ISSUE THREAD

**Issue by Mixie-12** [djmaze/tiddlywiki-docker#12]
Hi, love the tiddly!
The problem is that encryption does not work anymore.
Any solutions to this?

**Comment by dwurf** [comment]
Hi @Mixie-12,
Looking at the [TiddlyWiki docs](https://tiddlywiki.com/static/Encryption.html) on this topic, encryption only works "When used as a single HTML file". So, if you use your TiddlyWiki through this tiddlywiki-docker project you won't be able to use the built-in encryption feature.

I suggest you encrypt the disk where you store your tiddlers instead :smile:

**Comment by Mixie-12** [comment]
Oki, i think will go for encrypting my harddrive.
