### ISSUE TITLE
can we have an option to pick classic tiddlywiki for the docker image ?

### ISSUE THREAD

**Issue by anandkulkarnisg** [djmaze/tiddlywiki-docker#14]
I would like to help and contribute on this item if that is a possibility ? Instead of the current tiddlywiki version you have used , i would like to run the classic version of tiddlywiki on the docker image 
available at https://classic.tiddlywiki.com/ website.

**Comment by djmaze** [comment]
The classic version is technically totally different I suppose? So it probably would make more sense if you build a separate image for that.

**Comment by anandkulkarnisg** [comment]
I actually found out that there is tiddly desktop that seems to have become seperate and stand alone perhaps better to use it. anyway I think there is merit in building a seperate image for what I asked. will close this thx!!
