### ISSUE TITLE
Why docker container name changed everytime?

### ISSUE THREAD

**Issue by NMelis** [djmaze/tiddlywiki-docker#16]
I run  `docker run -d -p 8080:8080 -v C:\Users\username\Dropbox\mywiki\:/var/lib/tiddlywiki mazzolino/tiddlywiki` every restart computer
but everytime tiddlywiki-docker create a new continer, why doesn't it use already continer?
![изображение](https://user-images.githubusercontent.com/22614042/81731906-d6b0e800-94b9-11ea-94d4-fb736bb4d33c.png)

**Comment by NMelis** [comment]
And everytime container name is unique

**Comment by djmaze** [comment]
That's how Docker works. You could add `--restart=always`. Then the same container will be started over and over again automatically.

**Comment by NMelis** [comment]
Ou yeah, Thanks, I forgot about it. 
I think this needed add to README

**Comment by dwurf** [comment]
You can also `--name` your container, which will prevent creating a new container with the same name. A stopped container can be started with `docker start <name/id>`

**Comment by NMelis** [comment]
> 
> 
> You can also `--name` your container, which will prevent creating a new container with the same name. A stopped container can be started with `docker start <name/id>`

Cool! Thanks!
