### ISSUE TITLE
Way to passs the UID and GID?

### ISSUE THREAD

**Issue by Plaidstallion** [djmaze/tiddlywiki-docker#17]
It seems that the mywiki folder is owned by root:root. Is there a way to pass the desired UID/GID?

**Comment by djmaze** [comment]
You could use the `-u` switch to start the container with a different uid. That user has to exist in the container though, so you might have to adjust the Dockerfile to add a user with that id first.

Best would be change the container so the entrypoint accepts uid and gid and then `sudo`'s to the desired user. I am open for a PR, but not doing this myself.

**Comment by dwurf** [comment]
> That user has to exist in the container though

That's not true. Most processes run just fine with a uid even when that uid doesn't map to a real user. Here's how I run my containers:

`docker run -d --name wiki -u $(id -u):$(id -g) -p 8080:8080 -v $PWD/wiki:/var/lib/tiddlywiki mazzolino/tiddlywiki`

Just make sure to change the owner of any existing directory first, or this will fail.

`chown -R $(id -u):$(id -g) $PWD/wiki`

**Comment by Plaidstallion** [comment]
Thanks dwurf. It was indeed just as simple as adding the environment variables UID and GID.
