### ISSUE TITLE
Is this repo still mantained?

### ISSUE THREAD

**Issue by m0wer** [djmaze/tiddlywiki-docker#19]
@djmaze Thanks for the work BTW!

**Comment by dwurf** [comment]
My understanding is @djmaze is taking PRs but not actively using / developing the project - see [here](https://github.com/djmaze/tiddlywiki-docker/issues/9#issuecomment-409387587). He does respond to issues, and I tend to add my 2c when I see a new one too 😄

**Comment by djmaze** [comment]
Exactly. If there is someone keen to take over, I would be good with that as well.l

**Comment by m0wer** [comment]
Thank you both for your answers.

I forked the project and created an automated build for the Docker image. You can find them at:

* [m0wer/tiddlywiki-docker - GitHub](https://github.com/m0wer/tiddlywiki-docker)
* [m0wer/tiddlywiki - Docker Hub](https://hub.docker.com/r/m0wer/tiddlywiki)

I will be using this myself and update the Docker image weekly.

**Comment by elreydetoda** [comment]
@m0wer , since you are forking the project can you enable issues on that repo?

also, thank you all for maintaining this project before @m0wer :grin:

**Comment by m0wer** [comment]
> @m0wer , since you are forking the project can you enable issues on that repo?
> 
> also, thank you all for maintaining this project before @m0wer

Done, thanks for reminding me @elreydetoda.
