### ISSUE TITLE
get more plugins don`t work!

### ISSUE THREAD

**Issue by WuhanSy** [djmaze/tiddlywiki-docker#21]

**Comment by djmaze** [comment]
Works for me! What exactly happens for you?

**Comment by oncleben31** [comment]
When clicking `get more plugins` button, a popup is open but it is empty.

**Comment by sugarfunk** [comment]
Resolution here
https://github.com/Jermolene/TiddlyWiki5/issues/4570#issuecomment-615032818

**Comment by bionutrient** [comment]
> 
> 
> When clicking `get more plugins` button, a popup is open but it is empty.

Same with me!

**Comment by djmaze** [comment]
I am not maintaining this repository anymore. You might want to have a look at [m0wer's fork](https://github.com/m0wer/tiddlywiki-docker).
